#include "structures.h"

id_token *create_token(char *id, int line, int col);

is_program * insert_program(is_declarations_list * idl);
is_declarations_list * insert_declaration(is_declarations_list * head, is_declaration * id);
is_declaration * insert_var_declaration(is_var_spec * ivs);
is_declaration * insert_func_declaration(id_token * id, is_parameter * iparam, parameter_type type, is_func_body * ifb);
is_var_spec * insert_var_specifications(id_token * id, is_id_list * iis, parameter_type type);
is_id_list * insert_var_id(is_id_list * head, id_token * id );
is_parameter * insert_parameter(id_token * id, parameter_type type, is_id_type_list * iitl);
is_id_type_list * insert_id_type(is_id_type_list * head, id_token * id, parameter_type type);
is_func_body * insert_func_body(is_vars_and_statements_list * ivsl);
is_vars_and_statements_list * insert_var_dec(is_vars_and_statements_list * head, is_var_dec * ivd);
is_vars_and_statements_list * insert_statements(is_vars_and_statements_list * head, is_statement * is);
is_statement * insert_if_statement(is_expression_or_list * iel, is_statements_list * if_isl, is_statements_list * else_isl);
is_statement * insert_for_statement(is_expression_or_list * iel, is_statements_list* isl);
is_statement * insert_return_statement(is_expression_or_list * iel);
is_statement * insert_print_expr_statement(is_expression_or_list * iel);
is_statement * insert_print_str_statement(id_token * id);
is_statement * insert_assign_statement(id_token * id, is_expression_or_list * iel);
is_statement * insert_statements_list(is_statements_list * isl);
is_statement * insert_final_statement(is_final_statement * ifs);
is_final_statement * insert_final_state_args(is_parse_arguments * ipa);
is_final_statement * insert_final_state_func_inv(is_function_invocation * ifi);
is_statements_list * insert_statement_in_list(is_statements_list * head, is_statement * is);
is_parse_arguments * insert_parse_args( id_token * id, is_expression_or_list * iel);
is_function_invocation * insert_func_inv(id_token * id, is_expression_or_list * iel, is_func_inv_expr_list * head);
is_func_inv_expr_list * insert_expression(is_func_inv_expr_list * head, is_expression_or_list * ieol);
is_expression_or_list * insert_or(is_expression_or_list * ieol, next_oper * op, is_expression_and_list * ieal);
is_expression_and_list * insert_and(is_expression_and_list * ieal, next_oper * op, is_expression_comp_list * iecl);
is_expression_comp_list * insert_comp(is_expression_comp_list * iecl, next_oper * op, is_expression_sum_like_list * iesl);
is_expression_sum_like_list * insert_sum_like(is_expression_sum_like_list * iesl, next_oper * op, is_expression_star_like_list * iestl);
is_expression_star_like_list * insert_star_like(is_expression_star_like_list * iestl, next_oper * op, is_self_expression_list * isel);
is_self_expression_list * insert_self(is_self_expression_list * isel, next_oper * op, is_final_expression * ife);
is_final_expression * insert_intlit(id_token * id);
is_final_expression * insert_real(id_token * id);
is_final_expression * insert_id(id_token * id);
is_final_expression * insert_final_func_inv(is_function_invocation * ifi);
is_final_expression * insert_final_expr(is_expression_or_list*iel);
next_oper * insert_comp_oper(char * oper, next_oper * op);
next_oper * insert_sum_like_oper(char * oper, next_oper * op);
next_oper * insert_star_like_oper(char * oper, next_oper * op);
next_oper * insert_self_oper(char * oper, next_oper * op);
parameter_type insert_type(char * type);
